#ifndef TK
#    define TK(Id)
#endif

#ifndef TK_PUNCT
#    define TK_PUNCT(Id, Spelling) TK(Id)
#endif

#ifndef TK_MNEMONIC
#    define TK_MNEMONIC(Id, Spelling) TK(MN_##Id)
#endif

#ifndef TK_REGISTER
#    define TK_REGISTER(Id, Spelling) TK(REG_##Id)
#endif

///===--------------------------------------===///
/// Special tokens.
///===--------------------------------------===///

TK(INVALID)         // not a token
TK(END_OF_FILE)     // end of file

///===--------------------------------------===///
/// Assembler tokens.
///===--------------------------------------===///

TK(GLOBAL_LABEL)
TK(LOCAL_LABEL)
TK(IMMEDIATE)
TK(BYTE_STRING)
TK(STMT_END)

// Symbols
TK_PUNCT(COMMA, ",")

// MIPS General Purpose Registers
TK_REGISTER(R0, "r0")
TK_REGISTER(R1, "r1")
TK_REGISTER(R2, "r2")
TK_REGISTER(R3, "r3")
TK_REGISTER(R4, "r4")
TK_REGISTER(R5, "r5")
TK_REGISTER(R6, "r6")
TK_REGISTER(R7, "r7")
TK_REGISTER(R8, "r8")
TK_REGISTER(R9, "r9")
TK_REGISTER(R10, "r10")
TK_REGISTER(R11, "r11")
TK_REGISTER(R12, "r12")
TK_REGISTER(R13, "r13")
TK_REGISTER(R14, "r14")
TK_REGISTER(R15, "r15")
TK_REGISTER(R16, "r16")
TK_REGISTER(R17, "r17")
TK_REGISTER(R18, "r18")
TK_REGISTER(R19, "r19")
TK_REGISTER(R20, "r20")
TK_REGISTER(R21, "r21")
TK_REGISTER(R22, "r22")
TK_REGISTER(R23, "r23")
TK_REGISTER(R24, "r24")
TK_REGISTER(R25, "r25")
TK_REGISTER(R26, "r26")
TK_REGISTER(R27, "r27")
TK_REGISTER(R28, "r28")
TK_REGISTER(R29, "r29")
TK_REGISTER(R30, "r30")
TK_REGISTER(R31, "r31")

TK_REGISTER(ZERO, "zero")
TK_REGISTER(AT, "at")
TK_REGISTER(V0, "v0")
TK_REGISTER(V1, "v1")
TK_REGISTER(A0, "a0")
TK_REGISTER(A1, "a1")
TK_REGISTER(A2, "a2")
TK_REGISTER(A3, "a3")
TK_REGISTER(T0, "t0")
TK_REGISTER(T1, "t1")
TK_REGISTER(T2, "t2")
TK_REGISTER(T3, "t3")
TK_REGISTER(T4, "t4")
TK_REGISTER(T5, "t5")
TK_REGISTER(T6, "t6")
TK_REGISTER(T7, "t7")
TK_REGISTER(S0, "s0")
TK_REGISTER(S1, "s1")
TK_REGISTER(S2, "s2")
TK_REGISTER(S3, "s3")
TK_REGISTER(S4, "s4")
TK_REGISTER(S5, "s5")
TK_REGISTER(S6, "s6")
TK_REGISTER(S7, "s7")
TK_REGISTER(T8, "t8")
TK_REGISTER(T9, "t9")
TK_REGISTER(K0, "k0")
TK_REGISTER(K1, "k1")
TK_REGISTER(GP, "gp")
TK_REGISTER(SP, "sp")
TK_REGISTER(FP, "fp")
TK_REGISTER(RA, "ra")
TK_REGISTER(HI, "hi")
TK_REGISTER(LO, "lo")

// Directive mnemonics
TK_MNEMONIC(DB, "db")
TK_MNEMONIC(ENTRY, "entry")
TK_MNEMONIC(SECTION, "section")
TK_MNEMONIC(WEAK, "weak")

// Instruction mnemonics
TK_MNEMONIC(ABS, "abs")
TK_MNEMONIC(ADD, "add")
TK_MNEMONIC(ADDU, "addu")
TK_MNEMONIC(AND, "and")
TK_MNEMONIC(B, "b")
TK_MNEMONIC(BAL, "bal")
TK_MNEMONIC(BC2F, "bc2f")
TK_MNEMONIC(BC2T, "bc2t")
TK_MNEMONIC(BEQ, "beq")
TK_MNEMONIC(BGE, "bge")
TK_MNEMONIC(BGEU, "bgeu")
TK_MNEMONIC(BGEZ, "bgez")
TK_MNEMONIC(BGEZAL, "bgezal")
TK_MNEMONIC(BGT, "bgt")
TK_MNEMONIC(BGTU, "bgtu")
TK_MNEMONIC(BGTZ, "bgtz")
TK_MNEMONIC(BLE, "ble")
TK_MNEMONIC(BLEU, "bleu")
TK_MNEMONIC(BLEZ, "blez")
TK_MNEMONIC(BLT, "blt")
TK_MNEMONIC(BLTU, "bltu")
TK_MNEMONIC(BLTZ, "bltz")
TK_MNEMONIC(BLTZAL, "bltzal")
TK_MNEMONIC(BNE, "bne")
TK_MNEMONIC(BREAK, "break")
TK_MNEMONIC(CACHE, "cache")
TK_MNEMONIC(CFC2, "cfc2")
TK_MNEMONIC(CLO, "clo")
TK_MNEMONIC(CLZ, "clz")
TK_MNEMONIC(COP2, "cop2")
TK_MNEMONIC(CTC2, "ctc2")
TK_MNEMONIC(DERET, "deret")
TK_MNEMONIC(DIV, "div")
TK_MNEMONIC(DIVU, "divu")
TK_MNEMONIC(ERET, "eret")
TK_MNEMONIC(J, "j")
TK_MNEMONIC(JAL, "jal")
TK_MNEMONIC(JALR, "jalr")
TK_MNEMONIC(JR, "jr")
TK_MNEMONIC(LA, "la")
TK_MNEMONIC(LB, "lb")
TK_MNEMONIC(LBU, "lbu")
TK_MNEMONIC(LDC2, "ldc2")
TK_MNEMONIC(LH, "lh")
TK_MNEMONIC(LHU, "lhu")
TK_MNEMONIC(LI, "li")
TK_MNEMONIC(LL, "ll")
TK_MNEMONIC(LUI, "lui")
TK_MNEMONIC(LW, "lw")
TK_MNEMONIC(LWC2, "lwc2")
TK_MNEMONIC(LWL, "lwl")
TK_MNEMONIC(LWR, "lwr")
TK_MNEMONIC(MADD, "madd")
TK_MNEMONIC(MADDU, "maddu")
TK_MNEMONIC(MFC0, "mfc0")
TK_MNEMONIC(MFC2, "mfc2")
TK_MNEMONIC(MFHI, "mfhi")
TK_MNEMONIC(MFLO, "mflo")
TK_MNEMONIC(MOVE, "move")
TK_MNEMONIC(MOVN, "movn")
TK_MNEMONIC(MOVZ, "movz")
TK_MNEMONIC(MSUB, "msub")
TK_MNEMONIC(MSUBU, "msubu")
TK_MNEMONIC(MTC0, "mtc0")
TK_MNEMONIC(MTC2, "mtc2")
TK_MNEMONIC(MTHI, "mthi")
TK_MNEMONIC(MTLO, "mtlo")
TK_MNEMONIC(MUL, "mul")
TK_MNEMONIC(MULU, "mulu")
TK_MNEMONIC(MULT, "mult")
TK_MNEMONIC(MULTU, "multu")
TK_MNEMONIC(NEG, "neg")
TK_MNEMONIC(NEGU, "negu")
TK_MNEMONIC(NOT, "not")
TK_MNEMONIC(NOP, "nop")
TK_MNEMONIC(NOR, "nor")
TK_MNEMONIC(OR, "or")
TK_MNEMONIC(POP, "pop")
TK_MNEMONIC(PUSH, "push")
TK_MNEMONIC(PREF, "pref")
TK_MNEMONIC(REM, "rem")
TK_MNEMONIC(REMU, "remu")
TK_MNEMONIC(SB, "sb")
TK_MNEMONIC(SC, "sc")
TK_MNEMONIC(SDBBP, "sdbbp")
TK_MNEMONIC(SDC2, "sdc2")
TK_MNEMONIC(SGE, "sge")
TK_MNEMONIC(SGT, "sgt")
TK_MNEMONIC(SH, "sh")
TK_MNEMONIC(SLL, "sll")
TK_MNEMONIC(SLLV, "sllv")
TK_MNEMONIC(SLT, "slt")
TK_MNEMONIC(SLTIU, "sltiu")
TK_MNEMONIC(SLTU, "sltu")
TK_MNEMONIC(SRA, "sra")
TK_MNEMONIC(SRAV, "srav")
TK_MNEMONIC(SRL, "srl")
TK_MNEMONIC(SRLV, "srlv")
TK_MNEMONIC(SSNOP, "ssnop")
TK_MNEMONIC(SUB, "sub")
TK_MNEMONIC(SUBU, "subu")
TK_MNEMONIC(SW, "sw")
TK_MNEMONIC(SWC2, "swc2")
TK_MNEMONIC(SWL, "swl")
TK_MNEMONIC(SWR, "swr")
TK_MNEMONIC(SYNC, "sync")
TK_MNEMONIC(SYSCALL, "syscall")
TK_MNEMONIC(TEQ, "teq")
TK_MNEMONIC(TEQI, "teqi")
TK_MNEMONIC(TGE, "tge")
TK_MNEMONIC(TGEI, "tgei")
TK_MNEMONIC(TGEIU, "tgeiu")
TK_MNEMONIC(TGEU, "tgeu")
TK_MNEMONIC(TLBP, "tlbp")
TK_MNEMONIC(TLBR, "tlbr")
TK_MNEMONIC(TLBWI, "tlbwi")
TK_MNEMONIC(TLBWR, "tlbwr")
TK_MNEMONIC(TLT, "tlt")
TK_MNEMONIC(TLTU, "tltu")
TK_MNEMONIC(TNE, "tne")
TK_MNEMONIC(WAIT, "wait")
TK_MNEMONIC(XOR, "xor")

#undef TK_REGISTER
#undef TK_MNEMONIC
#undef TK_PUNCT
#undef TK
