/* -----------------------------------------------------------------------------
Part of the Choir Compiler Project under the GNU General Public License v2.0.
See the LICENSE file and LICENSES directory for more information.
SPDX-License-Identifier: GPL-2.0-only
----------------------------------------------------------------------------- */

#define NOB_IMPLEMENTATION
#define NOB_WARN_DEPRECATED
#define NOB_EXPERIMENTAL_DELETE_OLD
#define NOB_UNSTRIP_PREFIX
#include "build/nob.h"

#include "build/platform.h"
#include "build/directories.h"

typedef struct Config {
    bool enable_asan;
} Config;

#undef nob_shift
#define nob_shift(xs, xs_sz) (*(xs_sz) == 0 ? NULL : ((*(xs_sz))--, *(*(xs))++))

static bool
configure(int* argc, char*** argv, const char* config_header_path) {
    bool result = false;
    Config config = {0};

    const char* program_name = nob_shift(argv, argc);
    while (*argc > 0) {
        const char* opt = nob_shift(argv, argc);
        if (0 == strcmp(opt, "--") || *opt != '-') break;
        if (0 == strncmp(opt, "--asan=", 7)) {
            const char* arg = opt + 7;
            if (0 == strlen(arg)) {
                nob_log(NOB_ERROR, "Option '--asan' requires an argument.");
                goto fail;
            }
            if (0 == strcmp(arg, "on")) {
                config.enable_asan = true;
            } else if (0 == strcmp(arg, "off")) {
                config.enable_asan = false;
            } else {
                nob_log(NOB_ERROR, "Unrecognized argument to option '--asan': '%s'. Expected 'on' or 'off'.", arg);
                goto fail;
            }
        } else if (0 == strcmp(opt, "--asan")) {
            const char* arg = nob_shift(argv, argc);
            if (arg == NULL) {
                nob_log(NOB_ERROR, "Option '--asan' requires an argument.");
                goto fail;
            }
            if (0 == strcmp(arg, "on")) {
                config.enable_asan = true;
            } else if (0 == strcmp(arg, "off")) {
                config.enable_asan = false;
            } else {
                nob_log(NOB_ERROR, "Unrecognized argument to option '--asan': '%s'. Expected 'on' or 'off'.", arg);
                goto fail;
            }
        } else {
            nob_log(NOB_ERROR, "Unknown build configuration option '%s'.", opt);
            goto fail;
        }
    }

    Nob_String_Builder sb = {0};

    nob_sb_append_cstr(&sb, "/* -----------------------------------------------------------------------------\n");
    nob_sb_append_cstr(&sb, "Part of the Choir Compiler Project under the GNU General Public License v2.0.\n");
    nob_sb_append_cstr(&sb, "See the LICENSE file and LICENSES directory for more information.\n");
    nob_sb_append_cstr(&sb, "SPDX-License-Identifier: GPL-2.0-only\n");
    nob_sb_append_cstr(&sb, "--------------------------------------------------------------------------------\n");
    nob_sb_append_cstr(&sb, "This file was auto-generated by the project build tooling.\n");
    nob_sb_append_cstr(&sb, "Any changes to this file will be lost upon a build reconfigure.\n");
    nob_sb_append_cstr(&sb, "See 'nob.c' at the root of this repository or run './nob --help'.\n");
    nob_sb_append_cstr(&sb, "----------------------------------------------------------------------------- */\n");
    nob_sb_append_cstr(&sb, "\n");
    nob_sb_append_cstr(&sb, "#ifndef GAMEFU_NOB_BUILD_CONFIG_H_\n");
    nob_sb_append_cstr(&sb, "#define GAMEFU_NOB_BUILD_CONFIG_H_\n");
    nob_sb_append_cstr(&sb, "\n");
    nob_sb_append_cstr(&sb, "/* Whether or not to enable the address sanitizer. */\n");
    nob_sb_appendf(&sb, "#define CONFIG_ENABLE_ASAN  (%d)\n", config.enable_asan ? 1 : 0);
    nob_sb_append_cstr(&sb, "\n");
    nob_sb_append_cstr(&sb, "#endif /* GAMEFU_NOB_BUILD_CONFIG_H_ */\n");
    nob_sb_append_null(&sb);

    if (nob_file_exists(config_header_path)) {
        Nob_String_Builder contents = {0};
        if (!nob_read_entire_file(config_header_path, &contents)) goto fail;
        if (0 == strcmp(contents.items, sb.items)) goto success;
    }

    nob_log(NOB_INFO, "Generating '%s'", config_header_path);
    if (!nob_write_entire_file(config_header_path, sb.items, sb.count)) goto fail;

success:;
    result = true;
fail:;
    return result;
}

int
main(int argc, char** argv) {
    const char* build_nob_h = BUILD_DIR BUILD_PATH_SEP "nob.h";
    const char* build_config_h = BUILD_DIR BUILD_PATH_SEP "config.h";

    NOB_GO_REBUILD_URSELF_PLUS(argc, argv, build_nob_h);

    int result = 1;
    Nob_Cmd cmd = {0};

    if (!nob_mkdir_if_not_exists(BUILD_OUTPUT_DIR)) goto fail;

    if (!configure(&argc, &argv, build_config_h)) goto fail;
    assert(nob_file_exists(build_config_h));

    const char* build_src = BUILD_DIR BUILD_PATH_SEP "build.c";
    const char* build_exe = "." BUILD_PATH_SEP BUILD_OUTPUT_DIR BUILD_PATH_SEP "build" BUILD_EXE_EXT;

    const char* build_directories_h = BUILD_DIR BUILD_PATH_SEP "directories.h";
    const char* build_platform_h = BUILD_DIR BUILD_PATH_SEP "platform.h";

    const char* build_exe_deps[] = {
        build_src, build_nob_h, build_config_h, build_directories_h, build_platform_h
    };

    bool needs_rebuild = nob_needs_rebuild(
        build_exe, build_exe_deps, sizeof(build_exe_deps) / sizeof(*build_exe_deps)
    );

    if (needs_rebuild) {
        if (!BUILD_BOOTSTRAP(&cmd, build_exe, build_src)) goto fail;
    }

    nob_cmd_append(&cmd, build_exe);
    nob_da_append_many(&cmd, argv, (size_t) argc);
    if (!nob_cmd_run(&cmd, 0)) goto fail;

    result = 0;
fail:;
    nob_cmd_free(cmd);
    return result;
}
